### ISSUE TITLE
测试环境错误

### ISSUE THREAD

**Issue by Dianliang233** [Teahouse-Studios/bot#55]
```
[2021-08-24 14:35:52,582][INFO]: Running job "%s" (scheduled at %s)
Traceback (most recent call last):
  File "C:\Users\29178\Documents\GitHub\bot-v4\modules\mcv_rss\__init__.py", line 80, in jira
    verlist = getfileversions(version_file)
  File "C:\Users\29178\Documents\GitHub\bot-v4\modules\mcv_rss\__init__.py", line 16, in getfileversions
    a = open(path, 'a')
PermissionError: [Errno 13] Permission denied: 'C:\\mcjira_Java.txt'
Traceback (most recent call last):
  File "C:\Users\29178\Documents\GitHub\bot-v4\modules\mcv_rss\__init__.py", line 80, in jira
    verlist = getfileversions(version_file)
  File "C:\Users\29178\Documents\GitHub\bot-v4\modules\mcv_rss\__init__.py", line 16, in getfileversions
    a = open(path, 'a')
PermissionError: [Errno 13] Permission denied: 'C:\\mcjira_Bedrock.txt'
Traceback (most recent call last):
  File "C:\Users\29178\Documents\GitHub\bot-v4\modules\mcv_rss\__init__.py", line 80, in jira
    verlist = getfileversions(version_file)
  File "C:\Users\29178\Documents\GitHub\bot-v4\modules\mcv_rss\__init__.py", line 16, in getfileversions
    a = open(path, 'a')
PermissionError: [Errno 13] Permission denied: 'C:\\mcjira_Minecraft Dungeons.txt'
```

**Comment by OasisAkari** [comment]
Permission denied是你本地环境问题...确保你的环境添加了项目的路径到PYTHONPATH

**Comment by Dianliang233** [comment]
Permission denied: 'C:\\mcjira_Minecraft Dungeons.txt'

**Comment by OasisAkari** [comment]
看一下现在会不会再次出现，我本地环境一直都没有
